version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: "exit 0"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
    # for debugging
      # - "4000:4000"
  redis:
      image: redis
      ports:
          - "6379:6379"
      healthcheck:
        test: "exit 0"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  postgres_data:
    driver: local