// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CheckEasyjson ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CheckEasyjson ) UnmarshalJSON([]byte) error { return nil }
func ( CheckEasyjson ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CheckEasyjson ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CheckEasyjson *CheckEasyjson

func ( CheckJson ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CheckJson ) UnmarshalJSON([]byte) error { return nil }
func ( CheckJson ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CheckJson ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CheckJson *CheckJson

func ( CheckJsoniter ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CheckJsoniter ) UnmarshalJSON([]byte) error { return nil }
func ( CheckJsoniter ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CheckJsoniter ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CheckJsoniter *CheckJsoniter

func ( Profile ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Profile ) UnmarshalJSON([]byte) error { return nil }
func ( Profile ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Profile ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Profile *Profile

func ( Record ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Record ) UnmarshalJSON([]byte) error { return nil }
func ( Record ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Record ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Record *Record

func ( Welcome ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Welcome ) UnmarshalJSON([]byte) error { return nil }
func ( Welcome ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Welcome ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Welcome *Welcome
